//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.21 at 04:36:34 PM PKT 
//


package com.wso2.esb.mfs.jaxb;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.arcanainfo.wso2.esb.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Value_QNAME = new QName("", "Value");
    private final static QName _TransactionID_QNAME = new QName("", "TransactionID");
    private final static QName _Key_QNAME = new QName("", "Key");
    private final static QName _ResultDesc_QNAME = new QName("", "ResultDesc");
    private final static QName _OriginatorConversationID_QNAME = new QName("", "OriginatorConversationID");
    private final static QName _ResultCode_QNAME = new QName("", "ResultCode");
    private final static QName _ConversationID_QNAME = new QName("", "ConversationID");
    private final static QName _ResultType_QNAME = new QName("", "ResultType");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.arcanainfo.wso2.esb.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link ResultParameters }
     * 
     */
    public ResultParameters createResultParameters() {
        return new ResultParameters();
    }

    /**
     * Create an instance of {@link ResultParameter }
     * 
     */
    public ResultParameter createResultParameter() {
        return new ResultParameter();
    }

    /**
     * Create an instance of {@link ReferenceData }
     * 
     */
    public ReferenceData createReferenceData() {
        return new ReferenceData();
    }

    /**
     * Create an instance of {@link ReferenceItem }
     * 
     */
    public ReferenceItem createReferenceItem() {
        return new ReferenceItem();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransactionID")
    public JAXBElement<String> createTransactionID(String value) {
        return new JAXBElement<String>(_TransactionID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Key")
    public JAXBElement<String> createKey(String value) {
        return new JAXBElement<String>(_Key_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResultDesc")
    public JAXBElement<String> createResultDesc(String value) {
        return new JAXBElement<String>(_ResultDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OriginatorConversationID")
    public JAXBElement<String> createOriginatorConversationID(String value) {
        return new JAXBElement<String>(_OriginatorConversationID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResultCode")
    public JAXBElement<String> createResultCode(String value) {
        return new JAXBElement<String>(_ResultCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ConversationID")
    public JAXBElement<String> createConversationID(String value) {
        return new JAXBElement<String>(_ConversationID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResultType")
    public JAXBElement<BigInteger> createResultType(BigInteger value) {
        return new JAXBElement<BigInteger>(_ResultType_QNAME, BigInteger.class, null, value);
    }

}
